-- ==============================================================================
-- BẢNG TỪ VỰNG TIẾNG TRUNG THEO CẤP ĐỘ HSK 1 ĐẾN HSK 6 (VOCABULARIES)
-- Chạy file này trên Supabase SQL Editor
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.vocabularies (
  id TEXT PRIMARY KEY,
  level TEXT NOT NULL CHECK (level IN ('HSK 1', 'HSK 2', 'HSK 3', 'HSK 4', 'HSK 5', 'HSK 6')),
  topic TEXT,
  hanzi TEXT NOT NULL,
  pinyin TEXT NOT NULL,
  word_type TEXT,
  meaning TEXT NOT NULL,
  example_hanzi TEXT,
  example_meaning TEXT,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vocabularies_level ON public.vocabularies(level);
CREATE INDEX IF NOT EXISTS idx_vocabularies_topic ON public.vocabularies(topic);

ALTER TABLE public.vocabularies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép xem từ vựng công khai" ON public.vocabularies FOR SELECT USING (true);
CREATE POLICY "Cho phép staff quản lý từ vựng" ON public.vocabularies FOR ALL USING (true);

-- DỮ LIỆU TỪ VỰNG (314 TỪ)
INSERT INTO public.vocabularies (id, level, topic, hanzi, pinyin, word_type, meaning, example_hanzi, example_meaning, note)
VALUES
  ('TV-1-001', 'HSK 1', 'Cảm xúc', '爱', 'ài', 'Động từ', 'yêu', '我爱我的家人。', 'Tôi yêu gia đình tôi.', 'Đã duyệt (đợt 1)'),
  ('TV-1-002', 'HSK 1', 'Số đếm', '八', 'bā', 'Số từ', 'số tám', '我八岁了。', 'Tôi 8 tuổi rồi.', 'Đã duyệt (đợt 1)'),
  ('TV-1-003', 'HSK 1', 'Gia đình', '爸爸', 'bàba', 'Danh từ', 'bố, ba', '我爸爸是老师。', 'Bố tôi là giáo viên.', 'Đã duyệt (đợt 1)'),
  ('TV-1-004', 'HSK 1', 'Đồ vật', '杯子', 'bēizi', 'Danh từ', 'cái cốc', '这个杯子很漂亮。', 'Cái cốc này rất đẹp.', 'Đã duyệt (đợt 1)'),
  ('TV-1-005', 'HSK 1', 'Địa danh', '北京', 'Běijīng', 'Danh từ riêng', 'Bắc Kinh', '我想去北京。', 'Tôi muốn đi Bắc Kinh.', 'Đã duyệt (đợt 1)'),
  ('TV-1-006', 'HSK 1', 'Số lượng', '本', 'běn', 'Lượng từ', 'quyển, cuốn', '我有三本书。', 'Tôi có ba quyển sách.', 'Đã duyệt (đợt 1)'),
  ('TV-1-007', 'HSK 1', 'Chào hỏi', '不客气', 'bú kèqi', 'Cụm từ', 'không có gì', '谢谢你！不客气。', 'Cảm ơn bạn! Không có gì.', 'Đã duyệt (đợt 1)'),
  ('TV-1-008', 'HSK 1', 'Ngữ pháp cơ bản', '不', 'bù', 'Phó từ', 'không', '我不喜欢咖啡。', 'Tôi không thích cà phê.', 'Đã duyệt (đợt 1)'),
  ('TV-1-009', 'HSK 1', 'Ăn uống', '菜', 'cài', 'Danh từ', 'món ăn, rau', '这个菜很好吃。', 'Món này rất ngon.', 'Đã duyệt (đợt 1)'),
  ('TV-1-010', 'HSK 1', 'Ăn uống', '茶', 'chá', 'Danh từ', 'trà', '我喜欢喝茶。', 'Tôi thích uống trà.', 'Đã duyệt (đợt 1)'),
  ('TV-1-011', 'HSK 1', 'Ăn uống', '吃', 'chī', 'Động từ', 'ăn', '我们一起吃饭吧。', 'Chúng ta cùng ăn cơm đi.', 'Đã duyệt (đợt 1)'),
  ('TV-1-012', 'HSK 1', 'Giao thông', '出租车', 'chūzūchē', 'Danh từ', 'xe taxi', '我坐出租车去学校。', 'Tôi đi taxi đến trường.', 'Đã duyệt (đợt 1)'),
  ('TV-1-013', 'HSK 1', 'Giao tiếp', '打电话', 'dǎ diànhuà', 'Cụm động từ', 'gọi điện thoại', '我给妈妈打电话。', 'Tôi gọi điện cho mẹ.', 'Đã duyệt (đợt 1)'),
  ('TV-1-014', 'HSK 1', 'Tính chất', '大', 'dà', 'Tính từ', 'to, lớn', '这个房子很大。', 'Ngôi nhà này rất lớn.', 'Đã duyệt (đợt 1)'),
  ('TV-1-015', 'HSK 1', 'Ngữ pháp cơ bản', '的', 'de', 'Trợ từ', '(trợ từ sở hữu)', '这是我的书。', 'Đây là sách của tôi.', 'Đã duyệt (đợt 1)'),
  ('TV-1-016', 'HSK 1', 'Thời gian', '点', 'diǎn', 'Lượng từ', 'giờ (đơn vị)', '现在几点？', 'Bây giờ mấy giờ?', 'Mới - cần duyệt'),
  ('TV-1-017', 'HSK 1', 'Đồ vật', '电脑', 'diànnǎo', 'Danh từ', 'máy tính', '我在用电脑。', 'Tôi đang dùng máy tính.', 'Mới - cần duyệt'),
  ('TV-1-018', 'HSK 1', 'Đồ vật', '电视', 'diànshì', 'Danh từ', 'ti vi', '他在看电视。', 'Anh ấy đang xem ti vi.', 'Mới - cần duyệt'),
  ('TV-1-019', 'HSK 1', 'Giải trí', '电影', 'diànyǐng', 'Danh từ', 'phim', '我们去看电影吧。', 'Chúng ta đi xem phim đi.', 'Mới - cần duyệt'),
  ('TV-1-020', 'HSK 1', 'Đời sống', '东西', 'dōngxi', 'Danh từ', 'đồ vật', '这是什么东西？', 'Đây là cái gì vậy?', 'Mới - cần duyệt'),
  ('TV-1-021', 'HSK 1', 'Ngữ pháp cơ bản', '都', 'dōu', 'Phó từ', 'đều', '我们都是学生。', 'Chúng tôi đều là học sinh.', 'Mới - cần duyệt'),
  ('TV-1-022', 'HSK 1', 'Học tập', '读', 'dú', 'Động từ', 'đọc', '请大声读。', 'Xin đọc to lên.', 'Mới - cần duyệt'),
  ('TV-1-023', 'HSK 1', 'Chào hỏi', '对不起', 'duìbuqǐ', 'Cụm từ', 'xin lỗi', '对不起，我错了。', 'Xin lỗi, tôi sai rồi.', 'Mới - cần duyệt'),
  ('TV-1-024', 'HSK 1', 'Tính chất', '多', 'duō', 'Tính từ', 'nhiều', '他有很多书。', 'Anh ấy có rất nhiều sách.', 'Mới - cần duyệt'),
  ('TV-1-025', 'HSK 1', 'Ngữ pháp cơ bản', '多少', 'duōshao', 'Đại từ nghi vấn', 'bao nhiêu', '这个多少钱？', 'Cái này bao nhiêu tiền?', 'Mới - cần duyệt'),
  ('TV-1-026', 'HSK 1', 'Gia đình', '儿子', 'érzi', 'Danh từ', 'con trai', '他有一个儿子。', 'Anh ấy có một con trai.', 'Mới - cần duyệt'),
  ('TV-1-027', 'HSK 1', 'Số đếm', '二', 'èr', 'Số từ', 'số hai', '现在是二月。', 'Bây giờ là tháng hai.', 'Mới - cần duyệt'),
  ('TV-1-028', 'HSK 1', 'Đời sống', '饭店', 'fàndiàn', 'Danh từ', 'nhà hàng, khách sạn', '我们去饭店吃饭。', 'Chúng ta đi nhà hàng ăn cơm.', 'Mới - cần duyệt'),
  ('TV-1-029', 'HSK 1', 'Giao thông', '飞机', 'fēijī', 'Danh từ', 'máy bay', '他坐飞机去北京。', 'Anh ấy đi máy bay đến Bắc Kinh.', 'Mới - cần duyệt'),
  ('TV-1-030', 'HSK 1', 'Thời gian', '分钟', 'fēnzhōng', 'Lượng từ', 'phút', '等五分钟。', 'Đợi năm phút.', 'Mới - cần duyệt'),
  ('TV-1-031', 'HSK 1', 'Cảm xúc', '高兴', 'gāoxìng', 'Tính từ', 'vui', '认识你很高兴。', 'Rất vui được quen bạn.', 'Mới - cần duyệt'),
  ('TV-1-032', 'HSK 1', 'Ngữ pháp cơ bản', '个', 'gè', 'Lượng từ', 'cái, chiếc', '我有一个哥哥。', 'Tôi có một anh trai.', 'Mới - cần duyệt'),
  ('TV-1-033', 'HSK 1', 'Công việc', '工作', 'gōngzuò', 'Danh từ', 'công việc', '我在银行工作。', 'Tôi làm việc ở ngân hàng.', 'Mới - cần duyệt'),
  ('TV-1-034', 'HSK 1', 'Đời sống', '狗', 'gǒu', 'Danh từ', 'con chó', '我家有一只狗。', 'Nhà tôi có một con chó.', 'Mới - cần duyệt'),
  ('TV-1-035', 'HSK 1', 'Học tập', '汉语', 'Hànyǔ', 'Danh từ', 'tiếng Trung', '我学习汉语。', 'Tôi học tiếng Trung.', 'Mới - cần duyệt'),
  ('TV-1-036', 'HSK 1', 'Tính chất', '好', 'hǎo', 'Tính từ', 'tốt', '今天天气很好。', 'Hôm nay thời tiết rất tốt.', 'Mới - cần duyệt'),
  ('TV-1-037', 'HSK 1', 'Thời gian', '号', 'hào', 'Danh từ', 'ngày, số', '今天几号？', 'Hôm nay ngày mấy?', 'Mới - cần duyệt'),
  ('TV-1-038', 'HSK 1', 'Ăn uống', '喝', 'hē', 'Động từ', 'uống', '我想喝水。', 'Tôi muốn uống nước.', 'Mới - cần duyệt'),
  ('TV-1-039', 'HSK 1', 'Ngữ pháp cơ bản', '和', 'hé', 'Liên từ', 'và', '我和妈妈去商店。', 'Tôi và mẹ đi cửa hàng.', 'Mới - cần duyệt'),
  ('TV-1-040', 'HSK 1', 'Ngữ pháp cơ bản', '很', 'hěn', 'Phó từ', 'rất', '他很高。', 'Anh ấy rất cao.', 'Mới - cần duyệt'),
  ('TV-1-041', 'HSK 1', 'Vị trí', '后面', 'hòumiàn', 'Danh từ', 'phía sau', '学校在医院后面。', 'Trường học ở phía sau bệnh viện.', 'Mới - cần duyệt'),
  ('TV-1-042', 'HSK 1', 'Đời sống', '回', 'huí', 'Động từ', 'trở về', '我要回家了。', 'Tôi phải về nhà rồi.', 'Mới - cần duyệt'),
  ('TV-1-043', 'HSK 1', 'Ngữ pháp cơ bản', '会', 'huì', 'Động từ', 'biết, sẽ', '我会说汉语。', 'Tôi biết nói tiếng Trung.', 'Mới - cần duyệt'),
  ('TV-1-044', 'HSK 1', 'Ngữ pháp cơ bản', '几', 'jǐ', 'Đại từ nghi vấn', 'mấy', '你家有几口人？', 'Nhà bạn có mấy người?', 'Mới - cần duyệt'),
  ('TV-1-045', 'HSK 1', 'Gia đình', '家', 'jiā', 'Danh từ', 'nhà', '我家很大。', 'Nhà tôi rất lớn.', 'Mới - cần duyệt'),
  ('TV-1-046', 'HSK 1', 'Giao tiếp', '叫', 'jiào', 'Động từ', 'gọi, tên là', '我叫王明。', 'Tôi tên là Vương Minh.', 'Mới - cần duyệt'),
  ('TV-1-047', 'HSK 1', 'Thời gian', '今天', 'jīntiān', 'Danh từ', 'hôm nay', '今天是星期一。', 'Hôm nay là thứ hai.', 'Mới - cần duyệt'),
  ('TV-1-048', 'HSK 1', 'Số đếm', '九', 'jiǔ', 'Số từ', 'số chín', '现在九点。', 'Bây giờ 9 giờ.', 'Mới - cần duyệt'),
  ('TV-1-049', 'HSK 1', 'Đời sống', '开', 'kāi', 'Động từ', 'mở, lái', '请开门。', 'Xin mở cửa.', 'Mới - cần duyệt'),
  ('TV-1-050', 'HSK 1', 'Giải trí', '看', 'kàn', 'Động từ', 'xem, nhìn', '我喜欢看书。', 'Tôi thích đọc sách.', 'Mới - cần duyệt'),
  ('TV-1-051', 'HSK 1', 'Đời sống', '看见', 'kànjiàn', 'Động từ', 'nhìn thấy', '我看见他了。', 'Tôi nhìn thấy anh ấy rồi.', 'Mới - cần duyệt'),
  ('TV-1-052', 'HSK 1', 'Số học', '块', 'kuài', 'Lượng từ', 'đồng (tiền), miếng', '这个五块钱。', 'Cái này 5 đồng.', 'Mới - cần duyệt'),
  ('TV-1-053', 'HSK 1', 'Đời sống', '来', 'lái', 'Động từ', 'đến', '他明天来。', 'Ngày mai anh ấy đến.', 'Mới - cần duyệt'),
  ('TV-1-054', 'HSK 1', 'Học tập', '老师', 'lǎoshī', 'Danh từ', 'giáo viên', '她是我的老师。', 'Cô ấy là giáo viên của tôi.', 'Mới - cần duyệt'),
  ('TV-1-055', 'HSK 1', 'Ngữ pháp cơ bản', '了', 'le', 'Trợ từ', '(hoàn thành)', '我吃饭了。', 'Tôi ăn cơm rồi.', 'Mới - cần duyệt'),
  ('TV-1-056', 'HSK 1', 'Tính chất', '冷', 'lěng', 'Tính từ', 'lạnh', '今天很冷。', 'Hôm nay rất lạnh.', 'Mới - cần duyệt'),
  ('TV-1-057', 'HSK 1', 'Vị trí', '里', 'lǐ', 'Danh từ', 'bên trong', '书在包里。', 'Sách ở trong túi.', 'Mới - cần duyệt'),
  ('TV-1-058', 'HSK 1', 'Số đếm', '六', 'liù', 'Số từ', 'số sáu', '现在六点。', 'Bây giờ 6 giờ.', 'Mới - cần duyệt'),
  ('TV-1-059', 'HSK 1', 'Gia đình', '妈妈', 'māma', 'Danh từ', 'mẹ', '我妈妈很漂亮。', 'Mẹ tôi rất đẹp.', 'Mới - cần duyệt'),
  ('TV-1-060', 'HSK 1', 'Ngữ pháp cơ bản', '吗', 'ma', 'Trợ từ', '(nghi vấn)', '你是学生吗？', 'Bạn là học sinh à?', 'Mới - cần duyệt'),
  ('TV-1-061', 'HSK 1', 'Đời sống', '买', 'mǎi', 'Động từ', 'mua', '我想买衣服。', 'Tôi muốn mua quần áo.', 'Mới - cần duyệt'),
  ('TV-1-062', 'HSK 1', 'Đời sống', '猫', 'māo', 'Danh từ', 'con mèo', '这只猫很可爱。', 'Con mèo này rất đáng yêu.', 'Mới - cần duyệt'),
  ('TV-1-063', 'HSK 1', 'Chào hỏi', '没关系', 'méi guānxi', 'Cụm từ', 'không sao', '没关系，别担心。', 'Không sao, đừng lo.', 'Mới - cần duyệt'),
  ('TV-1-064', 'HSK 1', 'Ngữ pháp cơ bản', '没有', 'méiyǒu', 'Động từ', 'không có', '我没有钱。', 'Tôi không có tiền.', 'Mới - cần duyệt'),
  ('TV-1-065', 'HSK 1', 'Ăn uống', '米饭', 'mǐfàn', 'Danh từ', 'cơm', '我喜欢吃米饭。', 'Tôi thích ăn cơm.', 'Mới - cần duyệt'),
  ('TV-1-066', 'HSK 1', 'Thời gian', '明天', 'míngtiān', 'Danh từ', 'ngày mai', '明天见。', 'Hẹn gặp ngày mai.', 'Mới - cần duyệt'),
  ('TV-1-067', 'HSK 1', 'Giao tiếp', '名字', 'míngzi', 'Danh từ', 'tên', '你叫什么名字？', 'Bạn tên là gì?', 'Mới - cần duyệt'),
  ('TV-1-068', 'HSK 1', 'Ngữ pháp cơ bản', '哪', 'nǎ', 'Đại từ nghi vấn', 'nào', '你是哪国人？', 'Bạn là người nước nào?', 'Mới - cần duyệt'),
  ('TV-1-069', 'HSK 1', 'Ngữ pháp cơ bản', '哪儿', 'nǎr', 'Đại từ nghi vấn', 'đâu', '你在哪儿？', 'Bạn ở đâu?', 'Mới - cần duyệt'),
  ('TV-1-070', 'HSK 1', 'Ngữ pháp cơ bản', '那', 'nà', 'Đại từ chỉ định', 'kia, đó', '那是我的书。', 'Đó là sách của tôi.', 'Mới - cần duyệt'),
  ('TV-1-071', 'HSK 1', 'Ngữ pháp cơ bản', '呢', 'ne', 'Trợ từ', '(nghi vấn)', '我很好，你呢？', 'Tôi khỏe, còn bạn thì sao?', 'Mới - cần duyệt'),
  ('TV-1-072', 'HSK 1', 'Ngữ pháp cơ bản', '能', 'néng', 'Động từ', 'có thể', '我能帮你。', 'Tôi có thể giúp bạn.', 'Mới - cần duyệt'),
  ('TV-1-073', 'HSK 1', 'Ngữ pháp cơ bản', '你', 'nǐ', 'Đại từ', 'bạn', '你好吗？', 'Bạn khỏe không?', 'Mới - cần duyệt'),
  ('TV-1-074', 'HSK 1', 'Thời gian', '年', 'nián', 'Danh từ', 'năm', '今年是二零二六年。', 'Năm nay là năm 2026.', 'Mới - cần duyệt'),
  ('TV-1-075', 'HSK 1', 'Gia đình', '女儿', 'nǚ''ér', 'Danh từ', 'con gái', '她有一个女儿。', 'Cô ấy có một con gái.', 'Mới - cần duyệt'),
  ('TV-1-076', 'HSK 1', 'Giao tiếp', '朋友', 'péngyou', 'Danh từ', 'bạn bè', '他是我的朋友。', 'Anh ấy là bạn tôi.', 'Mới - cần duyệt'),
  ('TV-1-077', 'HSK 1', 'Tính chất', '漂亮', 'piàoliang', 'Tính từ', 'đẹp', '这件衣服很漂亮。', 'Cái áo này rất đẹp.', 'Mới - cần duyệt'),
  ('TV-1-078', 'HSK 1', 'Ăn uống', '苹果', 'píngguǒ', 'Danh từ', 'quả táo', '我喜欢吃苹果。', 'Tôi thích ăn táo.', 'Mới - cần duyệt'),
  ('TV-1-079', 'HSK 1', 'Số đếm', '七', 'qī', 'Số từ', 'số bảy', '现在七点。', 'Bây giờ 7 giờ.', 'Mới - cần duyệt'),
  ('TV-1-080', 'HSK 1', 'Đời sống', '钱', 'qián', 'Danh từ', 'tiền', '你有钱吗？', 'Bạn có tiền không?', 'Mới - cần duyệt'),
  ('TV-1-081', 'HSK 1', 'Vị trí', '前面', 'qiánmiàn', 'Danh từ', 'phía trước', '学校在前面。', 'Trường học ở phía trước.', 'Mới - cần duyệt'),
  ('TV-1-082', 'HSK 1', 'Giao tiếp', '请', 'qǐng', 'Động từ', 'mời, xin', '请坐。', 'Mời ngồi.', 'Mới - cần duyệt'),
  ('TV-1-083', 'HSK 1', 'Đời sống', '去', 'qù', 'Động từ', 'đi', '我们去学校。', 'Chúng ta đi đến trường.', 'Mới - cần duyệt'),
  ('TV-1-084', 'HSK 1', 'Tính chất', '热', 'rè', 'Tính từ', 'nóng', '今天很热。', 'Hôm nay rất nóng.', 'Mới - cần duyệt'),
  ('TV-1-085', 'HSK 1', 'Đời sống', '人', 'rén', 'Danh từ', 'người', '他是好人。', 'Anh ấy là người tốt.', 'Mới - cần duyệt'),
  ('TV-1-086', 'HSK 1', 'Giao tiếp', '认识', 'rènshi', 'Động từ', 'quen biết', '很高兴认识你。', 'Rất vui được quen bạn.', 'Mới - cần duyệt'),
  ('TV-1-087', 'HSK 1', 'Số đếm', '三', 'sān', 'Số từ', 'số ba', '现在三点。', 'Bây giờ 3 giờ.', 'Mới - cần duyệt'),
  ('TV-1-088', 'HSK 1', 'Đời sống', '商店', 'shāngdiàn', 'Danh từ', 'cửa hàng', '商店在哪儿？', 'Cửa hàng ở đâu?', 'Mới - cần duyệt'),
  ('TV-1-089', 'HSK 1', 'Vị trí', '上', 'shàng', 'Danh từ', 'trên, lên', '书在桌子上。', 'Sách ở trên bàn.', 'Mới - cần duyệt'),
  ('TV-1-090', 'HSK 1', 'Thời gian', '上午', 'shàngwǔ', 'Danh từ', 'buổi sáng', '我上午上课。', 'Buổi sáng tôi học.', 'Mới - cần duyệt'),
  ('TV-2-001', 'HSK 2', 'Đời sống', '帮助', 'bāngzhù', 'Động từ', 'giúp đỡ', '谢谢你帮助我。', 'Cảm ơn bạn đã giúp tôi.', 'Đã duyệt (đợt 1)'),
  ('TV-2-002', 'HSK 2', 'Đời sống', '报纸', 'bàozhǐ', 'Danh từ', 'tờ báo', '爸爸每天看报纸。', 'Bố tôi đọc báo mỗi ngày.', 'Đã duyệt (đợt 1)'),
  ('TV-2-003', 'HSK 2', 'Ngữ pháp', '比', 'bǐ', 'Giới từ', 'so với', '今天比昨天冷。', 'Hôm nay lạnh hơn hôm qua.', 'Đã duyệt (đợt 1)'),
  ('TV-2-004', 'HSK 2', 'Ngữ pháp', '别', 'bié', 'Phó từ', 'đừng', '别担心。', 'Đừng lo lắng.', 'Đã duyệt (đợt 1)'),
  ('TV-2-005', 'HSK 2', 'Du lịch', '宾馆', 'bīnguǎn', 'Danh từ', 'khách sạn', '我们住在这家宾馆。', 'Chúng tôi ở khách sạn này.', 'Đã duyệt (đợt 1)'),
  ('TV-2-006', 'HSK 2', 'Tính chất', '长', 'cháng', 'Tính từ', 'dài', '她的头发很长。', 'Tóc cô ấy rất dài.', 'Đã duyệt (đợt 1)'),
  ('TV-2-007', 'HSK 2', 'Giải trí', '唱歌', 'chànggē', 'Động từ', 'hát', '她唱歌唱得很好。', 'Cô ấy hát rất hay.', 'Đã duyệt (đợt 1)'),
  ('TV-2-008', 'HSK 2', 'Đời sống', '穿', 'chuān', 'Động từ', 'mặc (quần áo)', '今天很冷，多穿点衣服。', 'Hôm nay lạnh, mặc thêm đồ vào.', 'Đã duyệt (đợt 1)'),
  ('TV-2-009', 'HSK 2', 'Giao thông', '车站', 'chēzhàn', 'Danh từ', 'bến xe', '车站离这儿很近。', 'Bến xe gần đây.', 'Đã duyệt (đợt 1)'),
  ('TV-2-010', 'HSK 2', 'Gia đình', '弟弟', 'dìdi', 'Danh từ', 'em trai', '我弟弟今年十岁。', 'Em trai tôi năm nay 10 tuổi.', 'Đã duyệt (đợt 1)'),
  ('TV-2-011', 'HSK 2', 'Học tập', '懂', 'dǒng', 'Động từ', 'hiểu', '你懂我的意思吗？', 'Bạn hiểu ý tôi không?', 'Đã duyệt (đợt 1)'),
  ('TV-2-012', 'HSK 2', 'Đời sống', '房间', 'fángjiān', 'Danh từ', 'phòng', '这个房间很干净。', 'Phòng này rất sạch.', 'Đã duyệt (đợt 1)'),
  ('TV-2-013', 'HSK 2', 'Đời sống', '服务员', 'fúwùyuán', 'Danh từ', 'nhân viên phục vụ', '服务员，请给我一杯水。', 'Phục vụ ơi, cho tôi một cốc nước.', 'Đã duyệt (đợt 1)'),
  ('TV-2-014', 'HSK 2', 'Tính chất', '高', 'gāo', 'Tính từ', 'cao', '他比我高。', 'Anh ấy cao hơn tôi.', 'Đã duyệt (đợt 1)'),
  ('TV-2-015', 'HSK 2', 'Đời sống', '关', 'guān', 'Động từ', 'đóng, tắt', '请关门。', 'Làm ơn đóng cửa lại.', 'Đã duyệt (đợt 1)'),
  ('TV-2-016', 'HSK 2', 'Ngữ khí', '啊', 'a', 'Trợ từ', 'à', '啊，真漂亮！', 'À, đẹp thật!', 'Mới - cần duyệt'),
  ('TV-2-017', 'HSK 2', 'Gia đình', '阿姨', 'āyí', 'Danh từ', 'dì, cô', '这是我阿姨。', 'Đây là dì của tôi.', 'Mới - cần duyệt'),
  ('TV-2-018', 'HSK 2', 'Tính chất', '矮', 'ǎi', 'Tính từ', 'thấp', '他比较矮。', 'Anh ấy khá thấp.', 'Mới - cần duyệt'),
  ('TV-2-019', 'HSK 2', 'Giải trí', '爱好', 'àihào', 'Danh từ', 'sở thích', '你有什么爱好？', 'Bạn có sở thích gì?', 'Mới - cần duyệt'),
  ('TV-2-020', 'HSK 2', 'Tính chất', '白', 'bái', 'Tính từ', 'màu trắng', '这件衣服是白的。', 'Cái áo này màu trắng.', 'Mới - cần duyệt'),
  ('TV-2-021', 'HSK 2', 'Số đếm', '百', 'bǎi', 'Số từ', 'trăm', '这本书一百页。', 'Quyển sách này 100 trang.', 'Mới - cần duyệt'),
  ('TV-2-022', 'HSK 2', 'Đời sống', '搬', 'bān', 'Động từ', 'chuyển (nhà)', '我们要搬家了。', 'Chúng tôi sắp chuyển nhà.', 'Mới - cần duyệt'),
  ('TV-2-023', 'HSK 2', 'Công việc', '办公室', 'bàngōngshì', 'Danh từ', 'văn phòng', '他在办公室工作。', 'Anh ấy làm việc ở văn phòng.', 'Mới - cần duyệt'),
  ('TV-2-024', 'HSK 2', 'Đời sống', '帮', 'bāng', 'Động từ', 'giúp', '我帮你拿东西。', 'Tôi giúp bạn cầm đồ.', 'Mới - cần duyệt'),
  ('TV-2-025', 'HSK 2', 'Ngữ pháp', '比如', 'bǐrú', 'Liên từ', 'ví dụ như', '水果，比如苹果、香蕉。', 'Hoa quả, ví dụ như táo, chuối.', 'Mới - cần duyệt'),
  ('TV-2-026', 'HSK 2', 'Đời sống', '变', 'biàn', 'Động từ', 'thay đổi', '天气变冷了。', 'Thời tiết trở lạnh rồi.', 'Mới - cần duyệt'),
  ('TV-2-027', 'HSK 2', 'Xã hội', '别人', 'biéren', 'Đại từ', 'người khác', '不要打扰别人。', 'Đừng làm phiền người khác.', 'Mới - cần duyệt'),
  ('TV-2-028', 'HSK 2', 'Đồ vật', '冰箱', 'bīngxiāng', 'Danh từ', 'tủ lạnh', '牛奶在冰箱里。', 'Sữa ở trong tủ lạnh.', 'Mới - cần duyệt'),
  ('TV-2-029', 'HSK 2', 'Ngữ pháp', '不但', 'búdàn', 'Liên từ', 'không những', '他不但聪明而且努力。', 'Anh ấy không những thông minh mà còn chăm chỉ.', 'Mới - cần duyệt'),
  ('TV-2-030', 'HSK 2', 'Ngữ pháp', '不过', 'búguò', 'Liên từ', 'nhưng', '我想去，不过没有时间。', 'Tôi muốn đi, nhưng không có thời gian.', 'Mới - cần duyệt'),
  ('TV-2-031', 'HSK 2', 'Ngữ pháp', '才', 'cái', 'Phó từ', 'mới (vừa)', '他才来。', 'Anh ấy mới đến.', 'Mới - cần duyệt'),
  ('TV-2-032', 'HSK 2', 'Ăn uống', '菜单', 'càidān', 'Danh từ', 'thực đơn', '请给我菜单。', 'Cho tôi xin thực đơn.', 'Mới - cần duyệt'),
  ('TV-2-033', 'HSK 2', 'Đời sống', '参加', 'cānjiā', 'Động từ', 'tham gia', '我想参加比赛。', 'Tôi muốn tham gia cuộc thi.', 'Mới - cần duyệt'),
  ('TV-2-034', 'HSK 2', 'Thiên nhiên', '草', 'cǎo', 'Danh từ', 'cỏ', '公园里有很多草。', 'Trong công viên có nhiều cỏ.', 'Mới - cần duyệt'),
  ('TV-2-035', 'HSK 2', 'Đời sống', '层', 'céng', 'Lượng từ', 'tầng', '我家在三层。', 'Nhà tôi ở tầng ba.', 'Mới - cần duyệt'),
  ('TV-2-036', 'HSK 2', 'Thời gian', '差', 'chà', 'Động từ', 'kém, thiếu', '现在差五分七点。', 'Bây giờ 7 giờ kém 5 phút.', 'Mới - cần duyệt'),
  ('TV-2-037', 'HSK 2', 'Ăn uống', '尝', 'cháng', 'Động từ', 'nếm', '你尝尝这个菜。', 'Bạn nếm thử món này đi.', 'Mới - cần duyệt'),
  ('TV-2-038', 'HSK 2', 'Ngữ pháp', '常常', 'chángcháng', 'Phó từ', 'thường thường', '我常常去图书馆。', 'Tôi thường xuyên đi thư viện.', 'Mới - cần duyệt'),
  ('TV-2-039', 'HSK 2', 'Đời sống', '场', 'chǎng', 'Lượng từ', 'trận, buổi', '昨天有一场雨。', 'Hôm qua có một trận mưa.', 'Mới - cần duyệt'),
  ('TV-2-040', 'HSK 2', 'Đời sống', '超市', 'chāoshì', 'Danh từ', 'siêu thị', '我去超市买东西。', 'Tôi đi siêu thị mua đồ.', 'Mới - cần duyệt'),
  ('TV-2-041', 'HSK 2', 'Đồ vật', '衬衫', 'chènshān', 'Danh từ', 'áo sơ mi', '他穿白衬衫。', 'Anh ấy mặc áo sơ mi trắng.', 'Mới - cần duyệt'),
  ('TV-2-042', 'HSK 2', 'Địa lý', '城市', 'chéngshì', 'Danh từ', 'thành phố', '这是一个大城市。', 'Đây là một thành phố lớn.', 'Mới - cần duyệt'),
  ('TV-2-043', 'HSK 2', 'Đời sống', '迟到', 'chídào', 'Động từ', 'đến muộn', '他今天迟到了。', 'Hôm nay anh ấy đến muộn.', 'Mới - cần duyệt'),
  ('TV-2-044', 'HSK 2', 'Đời sống', '出发', 'chūfā', 'Động từ', 'xuất phát', '我们八点出发。', 'Chúng ta xuất phát lúc 8 giờ.', 'Mới - cần duyệt'),
  ('TV-2-045', 'HSK 2', 'Đời sống', '出去', 'chūqù', 'Động từ', 'đi ra ngoài', '我要出去买菜。', 'Tôi phải ra ngoài mua đồ ăn.', 'Mới - cần duyệt'),
  ('TV-2-046', 'HSK 2', 'Đời sống', '出现', 'chūxiàn', 'Động từ', 'xuất hiện', '问题又出现了。', 'Vấn đề lại xuất hiện rồi.', 'Mới - cần duyệt'),
  ('TV-2-047', 'HSK 2', 'Ngữ pháp', '除了', 'chúle', 'Giới từ', 'ngoại trừ', '除了他，大家都来了。', 'Ngoại trừ anh ấy, mọi người đều đến.', 'Mới - cần duyệt'),
  ('TV-2-048', 'HSK 2', 'Đời sống', '厨房', 'chúfáng', 'Danh từ', 'nhà bếp', '妈妈在厨房做饭。', 'Mẹ đang nấu ăn trong bếp.', 'Mới - cần duyệt'),
  ('TV-2-049', 'HSK 2', 'Thời gian', '春', 'chūn', 'Danh từ', 'mùa xuân', '春天很暖和。', 'Mùa xuân rất ấm áp.', 'Mới - cần duyệt'),
  ('TV-2-050', 'HSK 2', 'Học tập', '词典', 'cídiǎn', 'Danh từ', 'từ điển', '我买了一本词典。', 'Tôi đã mua một quyển từ điển.', 'Mới - cần duyệt'),
  ('TV-2-051', 'HSK 2', 'Ngữ pháp', '从', 'cóng', 'Giới từ', 'từ', '我从家来。', 'Tôi từ nhà đến.', 'Mới - cần duyệt'),
  ('TV-2-052', 'HSK 2', 'Tính chất', '聪明', 'cōngming', 'Tính từ', 'thông minh', '这个孩子很聪明。', 'Đứa trẻ này rất thông minh.', 'Mới - cần duyệt'),
  ('TV-2-053', 'HSK 2', 'Giải trí', '打篮球', 'dǎ lánqiú', 'Cụm động từ', 'chơi bóng rổ', '他喜欢打篮球。', 'Anh ấy thích chơi bóng rổ.', 'Mới - cần duyệt'),
  ('TV-2-054', 'HSK 2', 'Đời sống', '打扫', 'dǎsǎo', 'Động từ', 'dọn dẹp', '我打扫房间。', 'Tôi dọn dẹp phòng.', 'Mới - cần duyệt'),
  ('TV-2-055', 'HSK 2', 'Đời sống', '打算', 'dǎsuàn', 'Động từ', 'dự định', '你打算去哪儿？', 'Bạn dự định đi đâu?', 'Mới - cần duyệt'),
  ('TV-2-056', 'HSK 2', 'Đời sống', '带', 'dài', 'Động từ', 'mang theo', '别忘了带伞。', 'Đừng quên mang ô.', 'Mới - cần duyệt'),
  ('TV-2-057', 'HSK 2', 'Ngữ pháp', '但是', 'dànshì', 'Liên từ', 'nhưng', '他很累，但是他还在工作。', 'Anh ấy rất mệt, nhưng vẫn đang làm việc.', 'Mới - cần duyệt'),
  ('TV-2-058', 'HSK 2', 'Ăn uống', '蛋糕', 'dàngāo', 'Danh từ', 'bánh ga tô', '生日快乐，这是你的蛋糕。', 'Chúc mừng sinh nhật, đây là bánh của bạn.', 'Mới - cần duyệt'),
  ('TV-2-059', 'HSK 2', 'Ngữ pháp', '当然', 'dāngrán', 'Phó từ', 'đương nhiên', '当然可以。', 'Đương nhiên là được.', 'Mới - cần duyệt'),
  ('TV-2-060', 'HSK 2', 'Đời sống', '到', 'dào', 'Động từ', 'đến', '我们到学校了。', 'Chúng tôi đến trường rồi.', 'Mới - cần duyệt'),
  ('TV-2-061', 'HSK 2', 'Đời sống', '地方', 'dìfang', 'Danh từ', 'nơi chốn', '这是个好地方。', 'Đây là một nơi tốt.', 'Mới - cần duyệt'),
  ('TV-2-062', 'HSK 2', 'Giao thông', '地铁', 'dìtiě', 'Danh từ', 'tàu điện ngầm', '我坐地铁上班。', 'Tôi đi tàu điện ngầm đi làm.', 'Mới - cần duyệt'),
  ('TV-2-063', 'HSK 2', 'Đời sống', '地图', 'dìtú', 'Danh từ', 'bản đồ', '给我看一下地图。', 'Cho tôi xem bản đồ.', 'Mới - cần duyệt'),
  ('TV-2-064', 'HSK 2', 'Đồ vật', '电梯', 'diàntī', 'Danh từ', 'thang máy', '我们坐电梯上去。', 'Chúng ta đi thang máy lên.', 'Mới - cần duyệt'),
  ('TV-2-065', 'HSK 2', 'Công nghệ', '电子邮件', 'diànzǐ yóujiàn', 'Danh từ', 'email', '请给我发电子邮件。', 'Hãy gửi email cho tôi.', 'Mới - cần duyệt'),
  ('TV-2-066', 'HSK 2', 'Thời gian', '冬', 'dōng', 'Danh từ', 'mùa đông', '冬天很冷。', 'Mùa đông rất lạnh.', 'Mới - cần duyệt'),
  ('TV-2-067', 'HSK 2', 'Thiên nhiên', '动物', 'dòngwù', 'Danh từ', 'động vật', '他喜欢小动物。', 'Anh ấy thích động vật nhỏ.', 'Mới - cần duyệt'),
  ('TV-2-068', 'HSK 2', 'Tính chất', '短', 'duǎn', 'Tính từ', 'ngắn', '这条裤子太短了。', 'Cái quần này quá ngắn.', 'Mới - cần duyệt'),
  ('TV-2-069', 'HSK 2', 'Đời sống', '段', 'duàn', 'Lượng từ', 'đoạn', '这段话很重要。', 'Đoạn văn này rất quan trọng.', 'Mới - cần duyệt'),
  ('TV-2-070', 'HSK 2', 'Sức khỏe', '锻炼', 'duànliàn', 'Động từ', 'rèn luyện', '我每天锻炼身体。', 'Tôi rèn luyện cơ thể mỗi ngày.', 'Mới - cần duyệt'),
  ('TV-2-071', 'HSK 2', 'Tính chất', '对', 'duì', 'Tính từ', 'đúng', '你说得对。', 'Bạn nói đúng.', 'Mới - cần duyệt'),
  ('TV-2-072', 'HSK 2', 'Ngữ pháp', '多么', 'duōme', 'Phó từ', 'biết bao', '这里多么漂亮啊！', 'Nơi đây đẹp biết bao!', 'Mới - cần duyệt'),
  ('TV-2-073', 'HSK 2', 'Ăn uống', '饿', 'è', 'Tính từ', 'đói', '我很饿。', 'Tôi rất đói.', 'Mới - cần duyệt'),
  ('TV-2-074', 'HSK 2', 'Ngữ pháp', '而且', 'érqiě', 'Liên từ', 'hơn nữa', '他很聪明，而且很努力。', 'Anh ấy rất thông minh, hơn nữa rất chăm chỉ.', 'Mới - cần duyệt'),
  ('TV-2-075', 'HSK 2', 'Cơ thể', '耳朵', 'ěrduo', 'Danh từ', 'tai', '他的耳朵很大。', 'Tai anh ấy rất to.', 'Mới - cần duyệt'),
  ('TV-2-076', 'HSK 2', 'Giao tiếp', '发', 'fā', 'Động từ', 'phát, gửi', '请发短信给我。', 'Hãy nhắn tin cho tôi.', 'Mới - cần duyệt'),
  ('TV-2-077', 'HSK 2', 'Sức khỏe', '发烧', 'fāshāo', 'Động từ', 'bị sốt', '我发烧了。', 'Tôi bị sốt rồi.', 'Mới - cần duyệt'),
  ('TV-2-078', 'HSK 2', 'Đời sống', '发现', 'fāxiàn', 'Động từ', 'phát hiện', '我发现了一个问题。', 'Tôi đã phát hiện một vấn đề.', 'Mới - cần duyệt'),
  ('TV-2-079', 'HSK 2', 'Tính chất', '方便', 'fāngbiàn', 'Tính từ', 'tiện lợi', '这样比较方便。', 'Như thế này tiện hơn.', 'Mới - cần duyệt'),
  ('TV-2-080', 'HSK 2', 'Học tập', '方法', 'fāngfǎ', 'Danh từ', 'phương pháp', '这个方法很好。', 'Phương pháp này rất tốt.', 'Mới - cần duyệt'),
  ('TV-2-081', 'HSK 2', 'Đời sống', '房子', 'fángzi', 'Danh từ', 'ngôi nhà', '他们买了新房子。', 'Họ đã mua nhà mới.', 'Mới - cần duyệt'),
  ('TV-2-082', 'HSK 2', 'Đời sống', '放', 'fàng', 'Động từ', 'đặt, để', '把书放在桌子上。', 'Đặt sách lên bàn.', 'Mới - cần duyệt'),
  ('TV-2-083', 'HSK 2', 'Cảm xúc', '放心', 'fàngxīn', 'Động từ', 'yên tâm', '你放心吧。', 'Bạn cứ yên tâm.', 'Mới - cần duyệt'),
  ('TV-2-084', 'HSK 2', 'Thời gian', '分', 'fēn', 'Lượng từ', 'phút', '现在两点十分。', 'Bây giờ 2 giờ 10 phút.', 'Mới - cần duyệt'),
  ('TV-2-085', 'HSK 2', 'Vị trí', '附近', 'fùjìn', 'Danh từ', 'gần đây', '附近有超市吗？', 'Gần đây có siêu thị không?', 'Mới - cần duyệt'),
  ('TV-2-086', 'HSK 2', 'Học tập', '复习', 'fùxí', 'Động từ', 'ôn tập', '我在复习汉语。', 'Tôi đang ôn tập tiếng Trung.', 'Mới - cần duyệt'),
  ('TV-2-087', 'HSK 2', 'Tính chất', '干净', 'gānjìng', 'Tính từ', 'sạch sẽ', '房间很干净。', 'Phòng rất sạch sẽ.', 'Mới - cần duyệt'),
  ('TV-2-088', 'HSK 2', 'Sức khỏe', '感冒', 'gǎnmào', 'Động từ', 'cảm cúm', '我感冒了。', 'Tôi bị cảm rồi.', 'Mới - cần duyệt'),
  ('TV-2-089', 'HSK 2', 'Cảm xúc', '感兴趣', 'gǎn xìngqù', 'Cụm động từ', 'hứng thú', '我对汉语感兴趣。', 'Tôi hứng thú với tiếng Trung.', 'Mới - cần duyệt'),
  ('TV-3-001', 'HSK 3', 'Tính chất', '安静', 'ānjìng', 'Tính từ', 'yên tĩnh', '图书馆很安静。', 'Thư viện rất yên tĩnh.', 'Đã duyệt (đợt 1)'),
  ('TV-3-002', 'HSK 3', 'Ngữ pháp', '把', 'bǎ', 'Giới từ', 'đem, lấy', '请把门关上。', 'Làm ơn đóng cửa lại.', 'Đã duyệt (đợt 1)'),
  ('TV-3-003', 'HSK 3', 'Học tập', '班', 'bān', 'Danh từ', 'lớp', '我们班有二十个学生。', 'Lớp chúng tôi có 20 học sinh.', 'Đã duyệt (đợt 1)'),
  ('TV-3-004', 'HSK 3', 'Đời sống', '办法', 'bànfǎ', 'Danh từ', 'cách, biện pháp', '这个问题有办法解决。', 'Vấn đề này có cách giải quyết.', 'Đã duyệt (đợt 1)'),
  ('TV-3-005', 'HSK 3', 'Số đếm', '半', 'bàn', 'Số từ', 'nửa', '现在是三点半。', 'Bây giờ là 3 giờ rưỡi.', 'Đã duyệt (đợt 1)'),
  ('TV-3-006', 'HSK 3', 'Đời sống', '帮忙', 'bāngmáng', 'Động từ', 'giúp đỡ', '你能帮我一个忙吗？', 'Bạn có thể giúp tôi một việc không?', 'Đã duyệt (đợt 1)'),
  ('TV-3-007', 'HSK 3', 'Đồ vật', '包', 'bāo', 'Danh từ', 'túi, gói', '这个包很好看。', 'Cái túi này rất đẹp.', 'Đã duyệt (đợt 1)'),
  ('TV-3-008', 'HSK 3', 'Ăn uống', '饱', 'bǎo', 'Tính từ', 'no', '我吃饱了。', 'Tôi ăn no rồi.', 'Đã duyệt (đợt 1)'),
  ('TV-3-009', 'HSK 3', 'Địa lý', '北方', 'běifāng', 'Danh từ', 'miền Bắc', '冬天北方很冷。', 'Mùa đông miền Bắc rất lạnh.', 'Đã duyệt (đợt 1)'),
  ('TV-3-010', 'HSK 3', 'Ngữ pháp', '被', 'bèi', 'Giới từ', 'bị (bị động)', '杯子被打破了。', 'Cái cốc bị vỡ rồi.', 'Đã duyệt (đợt 1)'),
  ('TV-3-011', 'HSK 3', 'Cơ thể', '鼻子', 'bízi', 'Danh từ', 'cái mũi', '他的鼻子很高。', 'Mũi anh ấy cao.', 'Đã duyệt (đợt 1)'),
  ('TV-3-012', 'HSK 3', 'Ngữ pháp', '比较', 'bǐjiào', 'Phó từ', 'tương đối, so sánh', '这道题比较难。', 'Bài này tương đối khó.', 'Đã duyệt (đợt 1)'),
  ('TV-3-013', 'HSK 3', 'Giải trí', '比赛', 'bǐsài', 'Danh từ', 'cuộc thi, trận đấu', '今天有一场足球比赛。', 'Hôm nay có một trận bóng đá.', 'Đã duyệt (đợt 1)'),
  ('TV-3-014', 'HSK 3', 'Ngữ pháp', '必须', 'bìxū', 'Phó từ', 'phải, bắt buộc', '你必须按时完成作业。', 'Bạn phải hoàn thành bài tập đúng giờ.', 'Đã duyệt (đợt 1)'),
  ('TV-3-015', 'HSK 3', 'Đời sống', '变化', 'biànhuà', 'Danh từ', 'sự thay đổi', '这个城市变化很大。', 'Thành phố này thay đổi rất nhiều.', 'Đã duyệt (đợt 1)'),
  ('TV-3-016', 'HSK 3', 'Ngữ pháp', '各', 'gè', 'Đại từ', 'mỗi, các', '各位好。', 'Chào mọi người.', 'Mới - cần duyệt'),
  ('TV-3-017', 'HSK 3', 'Ngữ pháp', '根据', 'gēnjù', 'Giới từ', 'căn cứ vào', '根据天气预报，明天会下雨。', 'Theo dự báo thời tiết, ngày mai sẽ mưa.', 'Mới - cần duyệt'),
  ('TV-3-018', 'HSK 3', 'Ngữ pháp', '跟', 'gēn', 'Giới từ', 'cùng với', '我跟你一起去。', 'Tôi đi cùng bạn.', 'Mới - cần duyệt'),
  ('TV-3-019', 'HSK 3', 'Ngữ pháp', '更', 'gèng', 'Phó từ', 'càng', '今天比昨天更热。', 'Hôm nay nóng hơn hôm qua.', 'Mới - cần duyệt'),
  ('TV-3-020', 'HSK 3', 'Giao thông', '公共汽车', 'gōnggòng qìchē', 'Danh từ', 'xe buýt', '我坐公共汽车上学。', 'Tôi đi xe buýt đến trường.', 'Mới - cần duyệt'),
  ('TV-3-021', 'HSK 3', 'Số học', '公斤', 'gōngjīn', 'Lượng từ', 'ki lô gam', '这个包五公斤。', 'Cái túi này 5 kg.', 'Mới - cần duyệt'),
  ('TV-3-022', 'HSK 3', 'Số học', '公里', 'gōnglǐ', 'Lượng từ', 'ki lô mét', '学校离家两公里。', 'Trường học cách nhà 2km.', 'Mới - cần duyệt'),
  ('TV-3-023', 'HSK 3', 'Đời sống', '公园', 'gōngyuán', 'Danh từ', 'công viên', '我们去公园散步。', 'Chúng ta đi công viên dạo bộ.', 'Mới - cần duyệt'),
  ('TV-3-024', 'HSK 3', 'Giải trí', '故事', 'gùshi', 'Danh từ', 'câu chuyện', '妈妈给我讲故事。', 'Mẹ kể chuyện cho tôi nghe.', 'Mới - cần duyệt'),
  ('TV-3-025', 'HSK 3', 'Thiên nhiên', '刮风', 'guāfēng', 'Động từ', 'có gió', '外面刮风了。', 'Bên ngoài có gió rồi.', 'Mới - cần duyệt'),
  ('TV-3-026', 'HSK 3', 'Xã hội', '关系', 'guānxi', 'Danh từ', 'quan hệ', '他们关系很好。', 'Quan hệ của họ rất tốt.', 'Mới - cần duyệt'),
  ('TV-3-027', 'HSK 3', 'Cảm xúc', '关心', 'guānxīn', 'Động từ', 'quan tâm', '老师很关心学生。', 'Giáo viên rất quan tâm học sinh.', 'Mới - cần duyệt'),
  ('TV-3-028', 'HSK 3', 'Ngữ pháp', '关于', 'guānyú', 'Giới từ', 'về, liên quan đến', '这是一本关于历史的书。', 'Đây là một quyển sách về lịch sử.', 'Mới - cần duyệt'),
  ('TV-3-029', 'HSK 3', 'Địa lý', '国家', 'guójiā', 'Danh từ', 'quốc gia', '你的国家在哪儿？', 'Đất nước bạn ở đâu?', 'Mới - cần duyệt'),
  ('TV-3-030', 'HSK 3', 'Ăn uống', '果汁', 'guǒzhī', 'Danh từ', 'nước ép trái cây', '我想喝果汁。', 'Tôi muốn uống nước ép.', 'Mới - cần duyệt'),
  ('TV-3-031', 'HSK 3', 'Đời sống', '过', 'guò', 'Động từ', 'trải qua, đi qua', '他过马路了。', 'Anh ấy đã qua đường.', 'Mới - cần duyệt'),
  ('TV-3-032', 'HSK 3', 'Ngữ pháp', '还是', 'háishi', 'Liên từ', 'hay là', '你喝茶还是咖啡？', 'Bạn uống trà hay cà phê?', 'Mới - cần duyệt'),
  ('TV-3-033', 'HSK 3', 'Cảm xúc', '害怕', 'hàipà', 'Động từ', 'sợ hãi', '我害怕黑暗。', 'Tôi sợ bóng tối.', 'Mới - cần duyệt'),
  ('TV-3-034', 'HSK 3', 'Cơ thể', '汗', 'hàn', 'Danh từ', 'mồ hôi', '运动以后出了很多汗。', 'Sau khi vận động ra rất nhiều mồ hôi.', 'Mới - cần duyệt'),
  ('TV-3-035', 'HSK 3', 'Ăn uống', '好吃', 'hǎochī', 'Tính từ', 'ngon', '这个菜很好吃。', 'Món này rất ngon.', 'Mới - cần duyệt'),
  ('TV-3-036', 'HSK 3', 'Giải trí', '好玩儿', 'hǎowánr', 'Tính từ', 'vui, thú vị', '这个游戏很好玩儿。', 'Trò chơi này rất thú vị.', 'Mới - cần duyệt'),
  ('TV-3-037', 'HSK 3', 'Đời sống', '号码', 'hàomǎ', 'Danh từ', 'số (điện thoại)', '请给我你的电话号码。', 'Cho tôi xin số điện thoại của bạn.', 'Mới - cần duyệt'),
  ('TV-3-038', 'HSK 3', 'Địa lý', '河', 'hé', 'Danh từ', 'con sông', '这条河很长。', 'Con sông này rất dài.', 'Mới - cần duyệt'),
  ('TV-3-039', 'HSK 3', 'Học tập', '黑板', 'hēibǎn', 'Danh từ', 'bảng đen', '老师在黑板上写字。', 'Giáo viên viết chữ lên bảng.', 'Mới - cần duyệt'),
  ('TV-3-040', 'HSK 3', 'Thời gian', '后来', 'hòulái', 'Danh từ', 'sau đó', '后来他回国了。', 'Sau đó anh ấy về nước.', 'Mới - cần duyệt'),
  ('TV-3-041', 'HSK 3', 'Du lịch', '护照', 'hùzhào', 'Danh từ', 'hộ chiếu', '别忘了带护照。', 'Đừng quên mang hộ chiếu.', 'Mới - cần duyệt'),
  ('TV-3-042', 'HSK 3', 'Thiên nhiên', '花', 'huā', 'Danh từ', 'hoa', '她喜欢买花。', 'Cô ấy thích mua hoa.', 'Mới - cần duyệt'),
  ('TV-3-043', 'HSK 3', 'Đời sống', '花园', 'huāyuán', 'Danh từ', 'vườn hoa', '我家有一个花园。', 'Nhà tôi có một vườn hoa.', 'Mới - cần duyệt'),
  ('TV-3-044', 'HSK 3', 'Giải trí', '画', 'huà', 'Động từ', 'vẽ', '他画画很好。', 'Anh ấy vẽ tranh rất đẹp.', 'Mới - cần duyệt'),
  ('TV-3-045', 'HSK 3', 'Tính chất', '坏', 'huài', 'Tính từ', 'hỏng', '我的手机坏了。', 'Điện thoại của tôi hỏng rồi.', 'Mới - cần duyệt'),
  ('TV-3-046', 'HSK 3', 'Xã hội', '环境', 'huánjìng', 'Danh từ', 'môi trường', '这里的环境很好。', 'Môi trường ở đây rất tốt.', 'Mới - cần duyệt'),
  ('TV-3-047', 'HSK 3', 'Đời sống', '换', 'huàn', 'Động từ', 'đổi', '我想换一件衣服。', 'Tôi muốn đổi một chiếc áo khác.', 'Mới - cần duyệt'),
  ('TV-3-048', 'HSK 3', 'Địa lý', '黄河', 'Huánghé', 'Danh từ riêng', 'Hoàng Hà', '黄河很长。', 'Hoàng Hà rất dài.', 'Mới - cần duyệt'),
  ('TV-3-049', 'HSK 3', 'Học tập', '回答', 'huídá', 'Động từ', 'trả lời', '请回答我的问题。', 'Hãy trả lời câu hỏi của tôi.', 'Mới - cần duyệt'),
  ('TV-3-050', 'HSK 3', 'Công việc', '会议', 'huìyì', 'Danh từ', 'cuộc họp', '今天有一个会议。', 'Hôm nay có một cuộc họp.', 'Mới - cần duyệt'),
  ('TV-3-051', 'HSK 3', 'Ngữ pháp', '或者', 'huòzhě', 'Liên từ', 'hoặc là', '你可以喝茶或者咖啡。', 'Bạn có thể uống trà hoặc cà phê.', 'Mới - cần duyệt'),
  ('TV-3-052', 'HSK 3', 'Ngữ pháp', '几乎', 'jīhū', 'Phó từ', 'hầu như', '我几乎每天都去。', 'Tôi hầu như ngày nào cũng đi.', 'Mới - cần duyệt'),
  ('TV-3-053', 'HSK 3', 'Đời sống', '机会', 'jīhuì', 'Danh từ', 'cơ hội', '这是个好机会。', 'Đây là một cơ hội tốt.', 'Mới - cần duyệt'),
  ('TV-3-054', 'HSK 3', 'Ngữ pháp', '极', 'jí', 'Phó từ', 'cực kỳ', '今天热极了。', 'Hôm nay nóng cực kỳ.', 'Mới - cần duyệt'),
  ('TV-3-055', 'HSK 3', 'Đời sống', '记得', 'jìde', 'Động từ', 'nhớ', '我记得他的名字。', 'Tôi nhớ tên anh ấy.', 'Mới - cần duyệt'),
  ('TV-3-056', 'HSK 3', 'Thời gian', '季节', 'jìjié', 'Danh từ', 'mùa', '春天是我最喜欢的季节。', 'Mùa xuân là mùa tôi thích nhất.', 'Mới - cần duyệt'),
  ('TV-3-057', 'HSK 3', 'Sức khỏe', '检查', 'jiǎnchá', 'Động từ', 'kiểm tra', '医生给我检查身体。', 'Bác sĩ khám sức khỏe cho tôi.', 'Mới - cần duyệt'),
  ('TV-3-058', 'HSK 3', 'Tính chất', '简单', 'jiǎndān', 'Tính từ', 'đơn giản', '这个问题很简单。', 'Vấn đề này rất đơn giản.', 'Mới - cần duyệt'),
  ('TV-3-059', 'HSK 3', 'Giao tiếp', '见面', 'jiànmiàn', 'Động từ', 'gặp mặt', '我们下午见面吧。', 'Chúng ta gặp mặt buổi chiều nhé.', 'Mới - cần duyệt'),
  ('TV-3-060', 'HSK 3', 'Sức khỏe', '健康', 'jiànkāng', 'Danh từ', 'sức khỏe', '祝你健康。', 'Chúc bạn sức khỏe.', 'Mới - cần duyệt'),
  ('TV-3-061', 'HSK 3', 'Học tập', '讲', 'jiǎng', 'Động từ', 'giảng, nói', '老师在讲课。', 'Giáo viên đang giảng bài.', 'Mới - cần duyệt'),
  ('TV-3-062', 'HSK 3', 'Học tập', '教', 'jiāo', 'Động từ', 'dạy', '她教我们汉语。', 'Cô ấy dạy chúng tôi tiếng Trung.', 'Mới - cần duyệt'),
  ('TV-3-063', 'HSK 3', 'Học tập', '教室', 'jiàoshì', 'Danh từ', 'phòng học', '学生在教室里上课。', 'Học sinh học trong phòng học.', 'Mới - cần duyệt'),
  ('TV-3-064', 'HSK 3', 'Đời sống', '街道', 'jiēdào', 'Danh từ', 'đường phố', '这条街道很热闹。', 'Con phố này rất nhộn nhịp.', 'Mới - cần duyệt'),
  ('TV-3-065', 'HSK 3', 'Xã hội', '结婚', 'jiéhūn', 'Động từ', 'kết hôn', '他们下个月结婚。', 'Tháng sau họ kết hôn.', 'Mới - cần duyệt'),
  ('TV-3-066', 'HSK 3', 'Đời sống', '结束', 'jiéshù', 'Động từ', 'kết thúc', '电影结束了。', 'Bộ phim kết thúc rồi.', 'Mới - cần duyệt'),
  ('TV-3-067', 'HSK 3', 'Giải trí', '节目', 'jiémù', 'Danh từ', 'chương trình', '这个节目很有意思。', 'Chương trình này rất thú vị.', 'Mới - cần duyệt'),
  ('TV-3-068', 'HSK 3', 'Xã hội', '节日', 'jiérì', 'Danh từ', 'ngày lễ', '春节是中国的节日。', 'Tết Nguyên đán là ngày lễ của Trung Quốc.', 'Mới - cần duyệt'),
  ('TV-3-069', 'HSK 3', 'Đời sống', '解决', 'jiějué', 'Động từ', 'giải quyết', '问题解决了。', 'Vấn đề đã được giải quyết.', 'Mới - cần duyệt'),
  ('TV-3-070', 'HSK 3', 'Đời sống', '借', 'jiè', 'Động từ', 'mượn', '我想借一本书。', 'Tôi muốn mượn một quyển sách.', 'Mới - cần duyệt'),
  ('TV-3-071', 'HSK 3', 'Ngữ pháp', '经常', 'jīngcháng', 'Phó từ', 'thường xuyên', '他经常迟到。', 'Anh ấy thường xuyên đến muộn.', 'Mới - cần duyệt'),
  ('TV-3-072', 'HSK 3', 'Đời sống', '经过', 'jīngguò', 'Động từ', 'trải qua, đi qua', '经过努力，他成功了。', 'Qua nỗ lực, anh ấy đã thành công.', 'Mới - cần duyệt'),
  ('TV-3-073', 'HSK 3', 'Công việc', '经理', 'jīnglǐ', 'Danh từ', 'giám đốc', '他是公司经理。', 'Anh ấy là giám đốc công ty.', 'Mới - cần duyệt'),
  ('TV-3-074', 'HSK 3', 'Thời gian', '久', 'jiǔ', 'Tính từ', 'lâu', '好久不见。', 'Lâu rồi không gặp.', 'Mới - cần duyệt'),
  ('TV-3-075', 'HSK 3', 'Tính chất', '旧', 'jiù', 'Tính từ', 'cũ', '这是一件旧衣服。', 'Đây là một cái áo cũ.', 'Mới - cần duyệt'),
  ('TV-3-076', 'HSK 3', 'Đời sống', '决定', 'juédìng', 'Động từ', 'quyết định', '我决定明天出发。', 'Tôi quyết định xuất phát vào ngày mai.', 'Mới - cần duyệt'),
  ('TV-3-077', 'HSK 3', 'Tính chất', '可爱', 'kě''ài', 'Tính từ', 'đáng yêu', '这只猫很可爱。', 'Con mèo này rất đáng yêu.', 'Mới - cần duyệt'),
  ('TV-3-078', 'HSK 3', 'Ngữ pháp', '可能', 'kěnéng', 'Phó từ', 'có thể', '他可能不来了。', 'Có thể anh ấy sẽ không đến.', 'Mới - cần duyệt'),
  ('TV-3-079', 'HSK 3', 'Ăn uống', '渴', 'kě', 'Tính từ', 'khát', '我很渴，想喝水。', 'Tôi rất khát, muốn uống nước.', 'Mới - cần duyệt'),
  ('TV-3-080', 'HSK 3', 'Đời sống', '客人', 'kèrén', 'Danh từ', 'khách', '今天家里有客人。', 'Hôm nay nhà có khách.', 'Mới - cần duyệt'),
  ('TV-3-081', 'HSK 3', 'Đồ vật', '空调', 'kōngtiáo', 'Danh từ', 'máy điều hòa', '房间里有空调。', 'Trong phòng có máy điều hòa.', 'Mới - cần duyệt'),
  ('TV-3-082', 'HSK 3', 'Thiên nhiên', '空气', 'kōngqì', 'Danh từ', 'không khí', '这里的空气很新鲜。', 'Không khí ở đây rất trong lành.', 'Mới - cần duyệt'),
  ('TV-3-083', 'HSK 3', 'Số học', '口', 'kǒu', 'Lượng từ', 'người (đếm nhân khẩu)', '我家有五口人。', 'Nhà tôi có 5 người.', 'Mới - cần duyệt'),
  ('TV-3-084', 'HSK 3', 'Cảm xúc', '哭', 'kū', 'Động từ', 'khóc', '孩子哭了。', 'Đứa trẻ khóc rồi.', 'Mới - cần duyệt'),
  ('TV-3-085', 'HSK 3', 'Đồ vật', '裤子', 'kùzi', 'Danh từ', 'quần', '他穿黑裤子。', 'Anh ấy mặc quần đen.', 'Mới - cần duyệt'),
  ('TV-3-086', 'HSK 3', 'Ăn uống', '筷子', 'kuàizi', 'Danh từ', 'đôi đũa', '请给我一双筷子。', 'Cho tôi xin đôi đũa.', 'Mới - cần duyệt'),
  ('TV-3-087', 'HSK 3', 'Tính chất', '蓝', 'lán', 'Tính từ', 'màu xanh lam', '天空是蓝色的。', 'Bầu trời màu xanh lam.', 'Mới - cần duyệt'),
  ('TV-3-088', 'HSK 3', 'Tính chất', '老', 'lǎo', 'Tính từ', 'già', '他年纪很老了。', 'Ông ấy tuổi đã cao rồi.', 'Mới - cần duyệt'),
  ('TV-3-089', 'HSK 3', 'Ngữ pháp', '离', 'lí', 'Giới từ', 'cách', '学校离我家很近。', 'Trường học cách nhà tôi rất gần.', 'Mới - cần duyệt'),
  ('TV-3-090', 'HSK 3', 'Đời sống', '离开', 'líkāi', 'Động từ', 'rời khỏi', '他离开了公司。', 'Anh ấy đã rời khỏi công ty.', 'Mới - cần duyệt'),
  ('TV-4-001', 'HSK 4', 'Cảm xúc', '爱情', 'àiqíng', 'Danh từ', 'tình yêu', '这是一个关于爱情的故事。', 'Đây là câu chuyện về tình yêu.', 'Đã duyệt (đợt 1)'),
  ('TV-4-002', 'HSK 4', 'Công việc', '安排', 'ānpái', 'Động từ', 'sắp xếp', '老师安排了很多作业。', 'Giáo viên đã sắp xếp nhiều bài tập.', 'Đã duyệt (đợt 1)'),
  ('TV-4-003', 'HSK 4', 'Đời sống', '安全', 'ānquán', 'Tính từ', 'an toàn', '开车要注意安全。', 'Lái xe phải chú ý an toàn.', 'Đã duyệt (đợt 1)'),
  ('TV-4-004', 'HSK 4', 'Đời sống', '按时', 'ànshí', 'Phó từ', 'đúng giờ', '请按时上课。', 'Xin hãy đến lớp đúng giờ.', 'Đã duyệt (đợt 1)'),
  ('TV-4-005', 'HSK 4', 'Ngữ pháp', '按照', 'ànzhào', 'Giới từ', 'theo, dựa theo', '请按照顺序排队。', 'Xin xếp hàng theo thứ tự.', 'Đã duyệt (đợt 1)'),
  ('TV-4-006', 'HSK 4', 'Số học', '百分之', 'bǎifēnzhī', 'Cụm từ', 'phần trăm', '这次考试及格率是百分之九十。', 'Tỷ lệ đạt của kỳ thi này là 90%.', 'Đã duyệt (đợt 1)'),
  ('TV-4-007', 'HSK 4', 'Đánh giá', '棒', 'bàng', 'Tính từ', 'giỏi, tuyệt', '你真棒！', 'Bạn thật giỏi!', 'Đã duyệt (đợt 1)'),
  ('TV-4-008', 'HSK 4', 'Ăn uống', '包子', 'bāozi', 'Danh từ', 'bánh bao', '我早上喜欢吃包子。', 'Buổi sáng tôi thích ăn bánh bao.', 'Đã duyệt (đợt 1)'),
  ('TV-4-009', 'HSK 4', 'Môi trường', '保护', 'bǎohù', 'Động từ', 'bảo vệ', '我们应该保护环境。', 'Chúng ta nên bảo vệ môi trường.', 'Đã duyệt (đợt 1)'),
  ('TV-4-010', 'HSK 4', 'Đời sống', '保证', 'bǎozhèng', 'Động từ', 'đảm bảo', '我保证按时完成。', 'Tôi đảm bảo hoàn thành đúng giờ.', 'Đã duyệt (đợt 1)'),
  ('TV-4-011', 'HSK 4', 'Học tập', '报名', 'bàomíng', 'Động từ', 'đăng ký', '我想报名参加汉语课。', 'Tôi muốn đăng ký học lớp tiếng Trung.', 'Đã duyệt (đợt 1)'),
  ('TV-4-012', 'HSK 4', 'Giao tiếp', '抱歉', 'bàoqiàn', 'Động từ', 'xin lỗi, áy náy', '对不起，我来晚了，很抱歉。', 'Xin lỗi, tôi đến muộn, thật áy náy.', 'Đã duyệt (đợt 1)'),
  ('TV-4-013', 'HSK 4', 'Số học', '倍', 'bèi', 'Lượng từ', 'lần (gấp)', '这个比那个大两倍。', 'Cái này to gấp đôi cái kia.', 'Đã duyệt (đợt 1)'),
  ('TV-4-014', 'HSK 4', 'Ngữ pháp', '本来', 'běnlái', 'Phó từ', 'vốn dĩ', '我本来打算今天去，但是下雨了。', 'Vốn dĩ tôi định đi hôm nay, nhưng trời mưa.', 'Đã duyệt (đợt 1)'),
  ('TV-4-015', 'HSK 4', 'Học tập', '毕业', 'bìyè', 'Động từ', 'tốt nghiệp', '我明年毕业。', 'Sang năm tôi tốt nghiệp.', 'Đã duyệt (đợt 1)'),
  ('TV-5-001', 'HSK 5', 'Cảm xúc', '哎', 'āi', 'Thán từ', 'ôi', '哎，真可惜！', 'Ôi, thật đáng tiếc!', 'Đã duyệt (đợt 1)'),
  ('TV-5-002', 'HSK 5', 'Đời sống', '爱惜', 'àixī', 'Động từ', 'trân trọng, quý tiếc', '我们要爱惜时间。', 'Chúng ta phải trân trọng thời gian.', 'Đã duyệt (đợt 1)'),
  ('TV-5-003', 'HSK 5', 'Cảm xúc', '安慰', 'ānwèi', 'Động từ', 'an ủi', '朋友安慰了她很久。', 'Bạn bè đã an ủi cô ấy rất lâu.', 'Đã duyệt (đợt 1)'),
  ('TV-5-004', 'HSK 5', 'Công nghệ', '安装', 'ānzhuāng', 'Động từ', 'lắp đặt, cài đặt', '请帮我安装这个软件。', 'Làm ơn giúp tôi cài đặt phần mềm này.', 'Đã duyệt (đợt 1)'),
  ('TV-5-005', 'HSK 5', 'Địa lý', '岸', 'àn', 'Danh từ', 'bờ (sông, biển)', '我们坐在河岸上休息。', 'Chúng tôi ngồi nghỉ trên bờ sông.', 'Đã duyệt (đợt 1)'),
  ('TV-5-006', 'HSK 5', 'Đời sống', '熬夜', 'áoyè', 'Động từ', 'thức khuya', '为了工作，他经常熬夜。', 'Vì công việc, anh ấy thường thức khuya.', 'Đã duyệt (đợt 1)'),
  ('TV-5-007', 'HSK 5', 'Đời sống', '把握', 'bǎwò', 'Động từ', 'nắm chắc, nắm bắt', '要把握好这次机会。', 'Phải nắm chắc cơ hội lần này.', 'Đã duyệt (đợt 1)'),
  ('TV-5-008', 'HSK 5', 'Đời sống', '摆', 'bǎi', 'Động từ', 'bày, đặt', '她把花瓶摆在桌子上。', 'Cô ấy đặt bình hoa trên bàn.', 'Đã duyệt (đợt 1)'),
  ('TV-5-009', 'HSK 5', 'Thời gian', '傍晚', 'bàngwǎn', 'Danh từ', 'chiều tối', '我们傍晚出发。', 'Chúng tôi xuất phát vào chiều tối.', 'Đã duyệt (đợt 1)'),
  ('TV-5-010', 'HSK 5', 'Đời sống', '包裹', 'bāoguǒ', 'Danh từ', 'bưu kiện', '我收到了一个包裹。', 'Tôi đã nhận được một bưu kiện.', 'Đã duyệt (đợt 1)'),
  ('TV-5-011', 'HSK 5', 'Đời sống', '保持', 'bǎochí', 'Động từ', 'giữ vững, duy trì', '请保持安静。', 'Xin giữ yên lặng.', 'Đã duyệt (đợt 1)'),
  ('TV-5-012', 'HSK 5', 'Cảm xúc', '悲观', 'bēiguān', 'Tính từ', 'bi quan', '别那么悲观。', 'Đừng bi quan như vậy.', 'Đã duyệt (đợt 1)'),
  ('TV-5-013', 'HSK 5', 'Học tập', '背景', 'bèijǐng', 'Danh từ', 'bối cảnh', '这个故事的背景很复杂。', 'Bối cảnh câu chuyện này rất phức tạp.', 'Đã duyệt (đợt 1)'),
  ('TV-5-014', 'HSK 5', 'Số học', '比例', 'bǐlì', 'Danh từ', 'tỷ lệ', '男女比例大概是一比一。', 'Tỷ lệ nam nữ khoảng 1:1.', 'Đã duyệt (đợt 1)'),
  ('TV-5-015', 'HSK 5', 'Đời sống', '必要', 'bìyào', 'Tính từ', 'cần thiết', '没有必要担心。', 'Không cần thiết phải lo lắng.', 'Đã duyệt (đợt 1)'),
  ('TV-6-001', 'HSK 6', 'Cảm xúc', '哎呀', 'āiyā', 'Thán từ', 'ôi trời', '哎呀，我忘带钥匙了！', 'Ôi trời, tôi quên mang chìa khóa rồi!', 'Đã duyệt (đợt 1)'),
  ('TV-6-002', 'HSK 6', 'Y tế', '癌症', 'áizhèng', 'Danh từ', 'bệnh ung thư', '他正在和癌症作斗争。', 'Anh ấy đang chiến đấu với bệnh ung thư.', 'Đã duyệt (đợt 1)'),
  ('TV-6-003', 'HSK 6', 'Xã hội', '爱戴', 'àidài', 'Động từ', 'kính yêu', '这位老师深受学生爱戴。', 'Vị giáo viên này được học sinh rất kính yêu.', 'Đã duyệt (đợt 1)'),
  ('TV-6-004', 'HSK 6', 'Đời sống', '昂贵', 'ángguì', 'Tính từ', 'đắt đỏ', '这块手表非常昂贵。', 'Chiếc đồng hồ này rất đắt đỏ.', 'Đã duyệt (đợt 1)'),
  ('TV-6-005', 'HSK 6', 'Học tập', '案例', 'ànlì', 'Danh từ', 'trường hợp điển hình', '老师给我们介绍了一个成功的案例。', 'Giáo viên giới thiệu một trường hợp thành công.', 'Đã duyệt (đợt 1)'),
  ('TV-6-006', 'HSK 6', 'Xã hội', '报复', 'bàofù', 'Động từ', 'trả thù', '他没有选择报复。', 'Anh ấy đã không chọn cách trả thù.', 'Đã duyệt (đợt 1)'),
  ('TV-6-007', 'HSK 6', 'Đời sống', '保姆', 'bǎomǔ', 'Danh từ', 'người giúp việc', '他们家请了一位保姆。', 'Gia đình họ thuê một người giúp việc.', 'Đã duyệt (đợt 1)'),
  ('TV-6-008', 'HSK 6', 'Cảm xúc', '悲哀', 'bēi''āi', 'Tính từ', 'đau buồn', '这是一件令人悲哀的事情。', 'Đây là một chuyện đáng buồn.', 'Đã duyệt (đợt 1)'),
  ('TV-6-009', 'HSK 6', 'Đánh giá', '卑鄙', 'bēibǐ', 'Tính từ', 'đê tiện', '他的手段很卑鄙。', 'Thủ đoạn của hắn rất đê tiện.', 'Đã duyệt (đợt 1)'),
  ('TV-6-010', 'HSK 6', 'Xã hội', '背叛', 'bèipàn', 'Động từ', 'phản bội', '他背叛了自己的朋友。', 'Anh ta đã phản bội bạn của mình.', 'Đã duyệt (đợt 1)'),
  ('TV-6-011', 'HSK 6', 'Ngôn ngữ', '比喻', 'bǐyù', 'Danh từ', 'ẩn dụ, ví von', '这个比喻很生动。', 'Cách ví von này rất sinh động.', 'Đã duyệt (đợt 1)'),
  ('TV-6-012', 'HSK 6', 'Cảm xúc', '鄙视', 'bǐshì', 'Động từ', 'khinh miệt', '大家都很鄙视这种行为。', 'Mọi người đều rất khinh miệt hành vi này.', 'Đã duyệt (đợt 1)'),
  ('TV-6-013', 'HSK 6', 'Ngữ pháp', '必然', 'bìrán', 'Phó từ', 'tất nhiên', '努力工作必然会有回报。', 'Làm việc chăm chỉ tất nhiên sẽ có đền đáp.', 'Đã duyệt (đợt 1)'),
  ('TV-6-014', 'HSK 6', 'Địa lý', '边疆', 'biānjiāng', 'Danh từ', 'biên cương', '他在边疆当了三年兵。', 'Anh ấy đã làm lính ở biên cương ba năm.', 'Đã duyệt (đợt 1)'),
  ('TV-6-015', 'HSK 6', 'Nghề nghiệp', '编辑', 'biānjí', 'Danh từ', 'biên tập viên', '她是一名杂志编辑。', 'Cô ấy là biên tập viên tạp chí.', 'Đã duyệt (đợt 1)')
ON CONFLICT (id) DO UPDATE SET
  level = EXCLUDED.level, topic = EXCLUDED.topic, hanzi = EXCLUDED.hanzi, pinyin = EXCLUDED.pinyin,
  word_type = EXCLUDED.word_type, meaning = EXCLUDED.meaning, example_hanzi = EXCLUDED.example_hanzi,
  example_meaning = EXCLUDED.example_meaning, note = EXCLUDED.note;